# Generated by Django 5.2.7 on 2025-10-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='video',
        ),
        migrations.AddField(
            model_name='anime',
            name='google_drive_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Google Диск'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
