# Generated by Django 5.2.7 on 2025-10-15 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_remove_anime_video_anime_google_drive_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name': 'Аниме', 'verbose_name_plural': 'Аниме'},
        ),
        migrations.RemoveField(
            model_name='anime',
            name='google_drive_url',
        ),
        migrations.AddField(
            model_name='anime',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='anime',
            name='poster',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='posters/', verbose_name='Постер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='video',
            field=models.URLField(default=django.utils.timezone.now, help_text='Используйте ссылку Google Drive для встраивания', verbose_name='Ссылка на видео'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
